/**
 * Questionnaire v1.0 — implementasi data dari docs/QUESTION_BANK.md.
 * Konten adalah data (ADR-003); di produksi ini di-seed ke tabel
 * questionnaire_versions/questions/question_options dan menjadi immutable
 * setelah PUBLISHED (FR-21).
 */
import type { Question, QuestionOption, Questionnaire, RecommendationCatalogItem } from './types'

/** Helper opsi skala maturitas: skor 0/25/50/75/100 sesuai urutan label. */
function ladder(...labels: string[]): QuestionOption[] {
  const step = labels.length > 1 ? 100 / (labels.length - 1) : 100
  return labels.map((label, i) => ({
    code: `opt_${Math.round(i * step)}`,
    label,
    score: Math.round(i * step),
  }))
}

/** Helper opsi dengan skor eksplisit. */
function opts(...pairs: [string, number][]): QuestionOption[] {
  return pairs.map(([label, score]) => ({ code: `opt_${score}`, label, score }))
}

const q = (x: Question): Question => x

export const QUESTIONS: Question[] = [
  // ── Section 0: profil (tidak diskor, tetapi dipakai untuk branching)
  q({ code: 'ORG-02', dimension_code: 'STR', type: 'single_choice', unscored: true, required: true, weight: 0,
      prompt: 'Berapa jumlah karyawan perusahaan Anda?',
      options: [
        { code: '1_9', label: '1–9 orang', score: 0 },
        { code: '10_49', label: '10–49 orang', score: 0 },
        { code: '50_99', label: '50–99 orang', score: 0 },
        { code: '100_499', label: '100–499 orang', score: 0 },
        { code: '500_999', label: '500–999 orang', score: 0 },
        { code: '1000_plus', label: '1000 orang atau lebih', score: 0 },
      ] }),

  // ── STR Strategi & Kepemimpinan
  q({ code: 'STR-01', dimension_code: 'STR', type: 'single_choice', weight: 3, required: true, in_quick_check: true,
      prompt: 'Apakah perusahaan punya tujuan bisnis spesifik yang ingin dicapai dengan AI?',
      help_text: 'Contoh tujuan spesifik: "menurunkan waktu balas keluhan dari 24 jam ke 2 jam".',
      options: ladder(
        'Belum pernah dibahas serius',
        'Pernah dibahas, belum ada keputusan',
        'Ada minat umum, belum ada target terukur',
        'Ada 1–2 use case dengan target terukur',
        'Ada portofolio use case berprioritas dengan target & pemilik') }),
  q({ code: 'STR-02', dimension_code: 'STR', type: 'single_choice', weight: 3, required: true, in_quick_check: true,
      prompt: 'Siapa yang mensponsori inisiatif AI di perusahaan?',
      options: ladder('Tidak ada', 'Staf yang tertarik', 'Manajer menengah',
        'Direktur/VP', 'CEO atau pemilik dengan mandat tertulis') }),
  q({ code: 'STR-03', dimension_code: 'STR', type: 'single_choice', weight: 2, required: true,
      prompt: 'Apakah ada anggaran yang dialokasikan untuk AI tahun ini?',
      options: ladder('Tidak ada', 'Ada wacana', 'Kurang dari Rp 100 juta',
        'Rp 100–500 juta', 'Lebih dari Rp 500 juta atau pos anggaran tetap') }),
  q({ code: 'STR-04', dimension_code: 'STR', type: 'single_choice', weight: 2, required: true,
      prompt: 'Bagaimana keputusan investasi teknologi diambil?',
      options: ladder('Ad-hoc oleh pemilik', 'Berdasarkan rekomendasi vendor',
        'Ada proses pengajuan', 'Ada business case tertulis',
        'Business case disertai review pasca-implementasi') }),
  q({ code: 'STR-05', dimension_code: 'STR', type: 'single_choice', weight: 2, required: true,
      prompt: 'Apakah ada rencana AI tertulis (roadmap atau strategi)?',
      options: ladder('Tidak ada', 'Draft informal', 'Dokumen disetujui dengan milestone') }),
  q({ code: 'STR-06', dimension_code: 'STR', type: 'scale_1_5', weight: 1, required: true,
      prompt: 'Seberapa besar toleransi manajemen terhadap eksperimen yang gagal?',
      help_text: '1 = sangat rendah, 5 = sangat tinggi.' }),

  // ── DAT Data (dimensi terberat, ada hard gate)
  q({ code: 'DAT-01', dimension_code: 'DAT', type: 'single_choice', weight: 4, required: true, in_quick_check: true,
      prompt: 'Di mana data operasional utama Anda disimpan?',
      options: ladder(
        'Kertas atau catatan pribadi',
        'Spreadsheet tersebar di banyak orang',
        'Beberapa aplikasi terpisah yang tidak terhubung',
        'Sistem terpusat (ERP/POS/CRM) untuk sebagian besar proses',
        'Sistem terpusat dengan data warehouse terkonsolidasi') }),
  q({ code: 'DAT-02', dimension_code: 'DAT', type: 'single_choice', weight: 4, required: true, in_quick_check: true,
      prompt: 'Berapa lama riwayat data transaksi yang tersedia dan dapat diakses?',
      options: ladder('Kurang dari 3 bulan', '3–12 bulan', '1–2 tahun',
        '2–3 tahun', 'Lebih dari 3 tahun secara konsisten') }),
  q({ code: 'DAT-03', dimension_code: 'DAT', type: 'single_choice', weight: 4, required: true, in_quick_check: true,
      prompt: 'Bagaimana kualitas data Anda (duplikat, kosong, format tidak konsisten)?',
      options: ladder(
        'Banyak masalah dan tidak pernah dibersihkan',
        'Diketahui bermasalah, dibersihkan manual saat perlu',
        'Pembersihan berkala secara manual',
        'Ada aturan validasi di titik input',
        'Ada pemantauan kualitas data otomatis dengan metrik') }),
  q({ code: 'DAT-04', dimension_code: 'DAT', type: 'single_choice', weight: 3, required: true, in_quick_check: true,
      prompt: 'Seberapa mudah tim Anda mengakses data operasional untuk analisis?',
      help_text: 'Contoh: jika analis harus menghubungi staf IT untuk minta ekspor, pilih opsi pertama.',
      options: ladder(
        'Harus minta manual ke IT dan menunggu berhari-hari',
        'Ada ekspor berkala mingguan atau bulanan',
        'Ada dashboard self-service terbatas',
        'Ada akses API atau warehouse yang terdokumentasi',
        'Real-time, bertata kelola, dan self-service') }),
  q({ code: 'DAT-05', dimension_code: 'DAT', type: 'single_choice', weight: 3, required: true,
      prompt: 'Apakah ada definisi metrik dan istilah bisnis yang disepakati bersama?',
      options: ladder('Tiap divisi punya definisi sendiri',
        'Sebagian disepakati secara lisan',
        'Ada kamus data atau metrik tertulis yang dipakai') }),
  q({ code: 'DAT-06', dimension_code: 'DAT', type: 'single_choice', weight: 2, required: true,
      prompt: 'Siapa yang bertanggung jawab atas data (data owner atau steward)?',
      options: ladder('Tidak ada', 'IT merangkap', 'Ada data owner per domain') }),
  q({ code: 'DAT-07', dimension_code: 'DAT', type: 'multi_choice', weight: 2, required: true, min_select: 0,
      prompt: 'Jenis data apa yang sudah Anda miliki dalam bentuk digital?',
      help_text: 'Pilih semua yang sesuai. Makin beragam, makin banyak peluang use case.',
      options: [
        { code: 'sales_tx', label: 'Transaksi penjualan', score: 100 },
        { code: 'customer', label: 'Data pelanggan', score: 100 },
        { code: 'inventory', label: 'Inventaris', score: 100 },
        { code: 'finance', label: 'Keuangan', score: 100 },
        { code: 'ops', label: 'Operasional atau produksi', score: 100 },
        { code: 'text_docs', label: 'Teks atau dokumen', score: 100 },
        { code: 'media', label: 'Gambar atau video', score: 100 },
        { code: 'sensor', label: 'Sensor atau IoT', score: 100 },
      ] }),
  q({ code: 'DAT-08', dimension_code: 'DAT', type: 'single_choice', weight: 2, required: true,
      prompt: 'Apakah data pelanggan Anda memiliki dasar pemrosesan atau consent yang tercatat?',
      options: ladder('Tidak tahu',
        'Ada kebijakan privasi tetapi consent tidak tercatat',
        'Consent tercatat dan dapat ditarik') }),

  // ── TEC Teknologi & Infrastruktur
  q({ code: 'TEC-01', dimension_code: 'TEC', type: 'single_choice', weight: 3, required: true, in_quick_check: true,
      prompt: 'Bagaimana kondisi infrastruktur sistem Anda?',
      options: [
        { code: 'none', label: 'Tidak ada sistem terkomputerisasi', score: 0 },
        { code: 'onprem_only', label: 'On-premise saja, tanpa rencana migrasi', score: 25 },
        { code: 'onprem_plan', label: 'On-premise dengan rencana migrasi', score: 50 },
        { code: 'hybrid', label: 'Hybrid cloud', score: 75 },
        { code: 'cloud_native', label: 'Cloud-native', score: 100 },
      ] }),
  q({ code: 'TEC-02', dimension_code: 'TEC', type: 'single_choice', weight: 3, required: true, in_quick_check: true,
      prompt: 'Apakah sistem inti Anda punya API untuk integrasi?',
      options: ladder('Tidak ada atau tidak tahu', 'Hanya ekspor file',
        'API terbatas dari vendor', 'API terdokumentasi untuk sebagian besar sistem',
        'Semua sistem terintegrasi via API atau event') }),
  q({ code: 'TEC-03', dimension_code: 'TEC', type: 'single_choice', weight: 2, required: true,
      prompt: 'Bagaimana sistem antar-divisi saling terhubung?',
      options: ladder('Tidak terhubung, entri ulang manual',
        'Integrasi titik-ke-titik yang ad-hoc',
        'Integrasi terkelola (iPaaS atau event bus)') }),
  // Branching (PRD §7): hanya relevan bila masih ada komponen on-premise.
  q({ code: 'TEC-04', dimension_code: 'TEC', type: 'single_choice', weight: 2, required: true,
      prompt: 'Apakah ada rencana dan anggaran modernisasi infrastruktur 12 bulan ke depan?',
      visibility_rule: { question: 'TEC-01', op: 'in', value: ['onprem_only', 'onprem_plan', 'hybrid'] },
      options: ladder('Tidak ada', 'Ada rencana tanpa anggaran', 'Ada rencana dengan anggaran disetujui') }),
  q({ code: 'TEC-05', dimension_code: 'TEC', type: 'single_choice', weight: 2, required: true,
      prompt: 'Apakah tim menggunakan kontrol versi dan proses rilis yang terkelola?',
      options: ladder('Tidak ada tim teknis internal', 'Ada, tetapi prosesnya manual', 'CI/CD otomatis') }),
  q({ code: 'TEC-06', dimension_code: 'TEC', type: 'boolean', weight: 2, required: true,
      prompt: 'Apakah perusahaan pernah menjalankan model atau analitik lanjutan di produksi?' }),
  q({ code: 'TEC-07', dimension_code: 'TEC', type: 'single_choice', weight: 1, required: true,
      prompt: 'Bagaimana kapasitas komputasi untuk beban kerja AI?',
      options: ladder('Tidak ada', 'Bisa sewa cloud sesuai kebutuhan', 'Sudah tersedia dan teranggarkan') }),

  // ── PPL SDM & Keterampilan
  q({ code: 'PPL-01', dimension_code: 'PPL', type: 'single_choice', weight: 3, required: true, in_quick_check: true,
      prompt: 'Apakah ada orang di perusahaan yang mampu mengolah dan menganalisis data?',
      options: ladder('Tidak ada', 'Ada yang mahir spreadsheet', 'Ada analis data khusus',
        'Ada tim data atau BI', 'Ada data scientist atau ML engineer') }),
  q({ code: 'PPL-02', dimension_code: 'PPL', type: 'single_choice', weight: 3, required: true, in_quick_check: true,
      prompt: 'Bagaimana manajemen mengambil keputusan sehari-hari?',
      options: ladder('Berbasis intuisi', 'Melihat laporan sesekali', 'Rutin memakai laporan',
        'Memakai dashboard dan metrik', 'Menguji hipotesis sebelum memutuskan') }),
  q({ code: 'PPL-03', dimension_code: 'PPL', type: 'single_choice', weight: 2, required: true,
      prompt: 'Apakah ada program pelatihan teknologi atau data untuk karyawan?',
      options: ladder('Tidak ada', 'Ad-hoc sesuai permintaan', 'Program terjadwal dengan anggaran') }),
  q({ code: 'PPL-04', dimension_code: 'PPL', type: 'single_choice', weight: 2, required: true,
      prompt: 'Bagaimana kesiapan karyawan menghadapi perubahan cara kerja?',
      options: ladder('Resistensi tinggi', 'Netral, perlu dorongan', 'Antusias dan sudah ada yang berinisiatif') }),
  q({ code: 'PPL-05', dimension_code: 'PPL', type: 'single_choice', weight: 2, required: true,
      prompt: 'Apakah ada karyawan yang sudah memakai alat AI dalam pekerjaannya?',
      options: ladder('Tidak ada atau dilarang', 'Beberapa memakai diam-diam',
        'Beberapa memakai secara terbuka', 'Banyak yang memakai dengan panduan',
        'Terstandarisasi dengan lisensi resmi') }),
  q({ code: 'PPL-06', dimension_code: 'PPL', type: 'single_choice', weight: 2, required: true,
      prompt: 'Bagaimana akses Anda ke mitra atau vendor teknologi tepercaya?',
      options: ladder('Tidak punya', 'Pernah bekerja sama', 'Ada kemitraan yang berjalan') }),
  // Branching: struktur tim khusus hanya relevan untuk organisasi besar.
  q({ code: 'PPL-07', dimension_code: 'PPL', type: 'single_choice', weight: 1, required: true,
      prompt: 'Apakah ada struktur tim data atau AI khusus?',
      visibility_rule: { question: 'ORG-02', op: 'in', value: ['100_499', '500_999', '1000_plus'] },
      options: ladder('Tidak ada', 'Fungsinya tersebar di beberapa peran', 'Ada tim khusus dengan pemimpin') }),

  // ── PRC Proses & Operasi
  q({ code: 'PRC-01', dimension_code: 'PRC', type: 'single_choice', weight: 3, required: true, in_quick_check: true,
      prompt: 'Seberapa terdokumentasi proses bisnis inti Anda?',
      options: ladder('Tidak tertulis, hanya di kepala orang', 'Sebagian kecil tertulis',
        'Proses utama tertulis', 'Sebagian besar tertulis dan diperbarui',
        'Semua tertulis dan diaudit berkala') }),
  q({ code: 'PRC-02', dimension_code: 'PRC', type: 'single_choice', weight: 3, required: true,
      prompt: 'Seberapa standar proses berjalan antar cabang atau tim?',
      options: ladder('Sangat bervariasi', 'Standar sebagian', 'Seragam dan terukur dengan SLA') }),
  q({ code: 'PRC-03', dimension_code: 'PRC', type: 'single_choice', weight: 2, required: true,
      prompt: 'Bagaimana tingkat otomasi proses Anda saat ini?',
      options: ladder('Semua manual', 'Otomasi sebatas spreadsheet',
        'Beberapa alur otomatis di aplikasi', 'Workflow lintas sistem sudah otomatis',
        'Otomasi dipantau dengan metrik') }),
  // Diagnostik untuk memilih use case; sengaja tidak diskor.
  q({ code: 'PRC-04', dimension_code: 'PRC', type: 'multi_choice', weight: 0, required: false, unscored: true,
      prompt: 'Proses mana yang paling memakan waktu manual di tempat Anda?',
      options: [
        { code: 'data_entry', label: 'Input data', score: 0 },
        { code: 'reporting', label: 'Pelaporan', score: 0 },
        { code: 'cs', label: 'Layanan pelanggan', score: 0 },
        { code: 'approval', label: 'Persetujuan', score: 0 },
        { code: 'reconciliation', label: 'Rekonsiliasi', score: 0 },
        { code: 'scheduling', label: 'Penjadwalan', score: 0 },
        { code: 'qc', label: 'Quality check', score: 0 },
      ] }),
  q({ code: 'PRC-05', dimension_code: 'PRC', type: 'single_choice', weight: 2, required: true,
      prompt: 'Apakah kinerja proses diukur dengan KPI?',
      options: ladder('Tidak diukur', 'Beberapa KPI dilaporkan bulanan', 'KPI real-time dengan pemilik yang jelas') }),

  // ── GOV Tata Kelola, Risiko & Kepatuhan
  q({ code: 'GOV-01', dimension_code: 'GOV', type: 'single_choice', weight: 3, required: true, in_quick_check: true,
      prompt: 'Apakah ada kebijakan tertulis tentang penggunaan AI?',
      options: ladder('Tidak ada', 'Sedang disusun', 'Ada, disosialisasikan, dan ditinjau berkala') }),
  q({ code: 'GOV-02', dimension_code: 'GOV', type: 'single_choice', weight: 3, required: true,
      prompt: 'Bagaimana kesiapan kepatuhan terhadap UU PDP No. 27/2022?',
      options: ladder('Belum tahu kewajibannya', 'Tahu tetapi belum bertindak',
        'Kebijakan privasi sudah ada', 'Ada pemetaan data pribadi dan prosedur hak subjek data',
        'Lengkap dengan penanggung jawab dan audit berkala') }),
  q({ code: 'GOV-03', dimension_code: 'GOV', type: 'single_choice', weight: 2, required: true,
      prompt: 'Apakah ada kontrol akses berbasis peran pada sistem data?',
      options: ladder('Akses dibagi bersama', 'Sebagian sistem sudah', 'Semua sistem dengan review akses berkala') }),
  q({ code: 'GOV-04', dimension_code: 'GOV', type: 'single_choice', weight: 2, required: true,
      prompt: 'Apakah ada proses manajemen risiko atau persetujuan untuk teknologi baru?',
      options: ladder('Tidak ada', 'Informal', 'Formal dengan daftar risiko') }),
  q({ code: 'GOV-05', dimension_code: 'GOV', type: 'boolean', weight: 1, required: true,
      prompt: 'Apakah ada jejak audit atas perubahan data penting?' }),
  q({ code: 'GOV-06', dimension_code: 'GOV', type: 'single_choice', weight: 1, required: true,
      prompt: 'Apakah ada regulasi sektoral yang mengikat bisnis Anda (OJK, Kemenkes, dan sejenisnya)?',
      options: opts(['Ada, tetapi belum dipetakan', 0], ['Ada dan sudah dipetakan', 50], ['Tidak ada', 100]) }),

  // ── FIN Finansial & Nilai
  q({ code: 'FIN-01', dimension_code: 'FIN', type: 'single_choice', weight: 3, required: true,
      prompt: 'Apakah Anda dapat mengukur biaya proses yang ingin diperbaiki?',
      options: ladder('Tidak tahu', 'Ada perkiraan kasar', 'Ada angka akurat per proses') }),
  q({ code: 'FIN-02', dimension_code: 'FIN', type: 'single_choice', weight: 3, required: true, in_quick_check: true,
      prompt: 'Berapa kesediaan investasi awal untuk pilot AI dalam 12 bulan ke depan?',
      options: ladder('Rp 0', 'Kurang dari Rp 50 juta', 'Rp 50–150 juta',
        'Rp 150–500 juta', 'Lebih dari Rp 500 juta') }),
  q({ code: 'FIN-03', dimension_code: 'FIN', type: 'single_choice', weight: 2, required: true,
      prompt: 'Berapa ekspektasi waktu balik modal Anda?',
      help_text: 'Ekspektasi yang terlalu cepat justru menandakan risiko kekecewaan.',
      options: opts(
        ['Kurang dari 3 bulan', 0],
        ['3–6 bulan', 50],
        ['Lebih dari 18 bulan', 75],
        ['6–18 bulan', 100]) }),
  q({ code: 'FIN-04', dimension_code: 'FIN', type: 'single_choice', weight: 2, required: true,
      prompt: 'Apakah ada kerangka evaluasi ROI untuk proyek teknologi?',
      options: ladder('Tidak ada', 'Ad-hoc', 'Terstandar dengan review pasca-implementasi') }),
]

export const QUESTIONNAIRE_V1: Questionnaire = {
  version: '1.0.0',
  rubric_version: '1.0.0',
  dimensions: [
    { code: 'STR', name: 'Strategi & Kepemimpinan', weight: 0.15 },
    { code: 'DAT', name: 'Data', weight: 0.25 },
    { code: 'TEC', name: 'Teknologi & Infrastruktur', weight: 0.15 },
    { code: 'PPL', name: 'SDM & Keterampilan', weight: 0.15 },
    { code: 'PRC', name: 'Proses & Operasi', weight: 0.10 },
    { code: 'GOV', name: 'Tata Kelola & Kepatuhan', weight: 0.10 },
    { code: 'FIN', name: 'Finansial & Nilai', weight: 0.10 },
  ],
  questions: QUESTIONS,
}

export const RECOMMENDATION_CATALOG: RecommendationCatalogItem[] = [
  {
    code: 'REC-DAT-001', dimension_code: 'DAT',
    title: 'Konsolidasikan data operasional ke satu sistem terpusat',
    body: 'Pilih satu sistem sumber kebenaran untuk transaksi inti, lalu migrasikan spreadsheet yang tersebar. Tanpa ini, setiap proyek AI akan menghabiskan 60–80% waktunya hanya untuk mengumpulkan data.',
    impact: 5, effort: 4, horizon: '3_6M', owner_role: 'Head of IT', cost_band: '100_500jt',
    triggers: [{ question_code: 'DAT-01', max_score: 25 }],
  },
  {
    code: 'REC-DAT-002', dimension_code: 'DAT',
    title: 'Terapkan validasi di titik input dan bersihkan master data',
    body: 'Tambahkan aturan wajib-isi, format terkunci, dan pencegahan duplikat pada formulir entri. Bersihkan data master pelanggan dan produk sekali secara menyeluruh.',
    impact: 5, effort: 2, horizon: '0_3M', owner_role: 'Manajer Operasional', cost_band: '10_30jt',
    triggers: [{ question_code: 'DAT-03', max_score: 25 }],
  },
  {
    code: 'REC-DAT-003', dimension_code: 'DAT',
    title: 'Susun kamus metrik bisnis bersama',
    body: 'Sepakati definisi tunggal untuk istilah seperti "pelanggan aktif" dan "penjualan bersih", lalu dokumentasikan dan pakai di semua laporan.',
    impact: 4, effort: 1, horizon: '0_3M', owner_role: 'Finance & Ops', cost_band: 'under_10jt',
    triggers: [{ question_code: 'DAT-05', max_score: 0 }],
  },
  {
    code: 'REC-DAT-004', dimension_code: 'DAT',
    title: 'Buka akses data self-service untuk tim analis',
    body: 'Sediakan dashboard atau akses baca ke warehouse agar analis tidak bergantung pada permintaan manual ke IT.',
    impact: 4, effort: 3, horizon: '3_6M', owner_role: 'Head of IT', cost_band: '30_100jt',
    triggers: [{ question_code: 'DAT-04', max_score: 25 }],
  },
  {
    code: 'REC-GOV-001', dimension_code: 'GOV',
    title: 'Petakan data pribadi dan susun prosedur hak subjek data (UU PDP)',
    body: 'Inventarisasi di mana data pribadi disimpan, tetapkan dasar pemrosesan, dan siapkan prosedur permintaan akses serta penghapusan data.',
    impact: 5, effort: 2, horizon: '0_3M', owner_role: 'Legal & Compliance', cost_band: '10_30jt',
    triggers: [{ question_code: 'GOV-02', max_score: 25 }],
  },
  {
    code: 'REC-GOV-002', dimension_code: 'GOV',
    title: 'Terbitkan kebijakan penggunaan AI internal',
    body: 'Atur data apa yang boleh dimasukkan ke alat AI publik, siapa yang menyetujui penggunaan baru, dan bagaimana hasil AI diverifikasi sebelum dipakai.',
    impact: 4, effort: 1, horizon: '0_3M', owner_role: 'C-Level', cost_band: 'under_10jt',
    triggers: [{ question_code: 'GOV-01', max_score: 50 }],
  },
  {
    code: 'REC-STR-001', dimension_code: 'STR',
    title: 'Jalankan lokakarya identifikasi use case dengan kriteria nilai',
    body: 'Kumpulkan kepala divisi selama satu hari, daftar masalah yang mahal dan berulang, lalu nilai tiap kandidat berdasar dampak dan ketersediaan data.',
    impact: 4, effort: 1, horizon: '0_3M', owner_role: 'C-Level', cost_band: 'under_10jt',
    triggers: [{ question_code: 'STR-01', max_score: 25 }],
  },
  {
    code: 'REC-STR-002', dimension_code: 'STR',
    title: 'Tunjuk sponsor eksekutif dengan mandat tertulis',
    body: 'Inisiatif AI tanpa sponsor level direksi hampir selalu berhenti saat berbenturan dengan prioritas operasional harian.',
    impact: 5, effort: 1, horizon: '0_3M', owner_role: 'CEO', cost_band: 'under_10jt',
    triggers: [{ question_code: 'STR-02', max_score: 50 }],
  },
  {
    code: 'REC-PPL-001', dimension_code: 'PPL',
    title: 'Latih 3–5 champion data internal',
    body: 'Pilih staf yang sudah mahir spreadsheet dari divisi berbeda, beri pelatihan analitik terstruktur, dan berikan waktu resmi untuk mengerjakan proyek data.',
    impact: 4, effort: 2, horizon: '0_3M', owner_role: 'HR & Head of IT', cost_band: '10_30jt',
    triggers: [{ question_code: 'PPL-01', max_score: 25 }],
  },
  {
    code: 'REC-PPL-002', dimension_code: 'PPL',
    title: 'Standarkan penggunaan asisten AI dengan lisensi resmi dan panduan',
    body: 'Karyawan yang memakai alat AI diam-diam menimbulkan risiko kebocoran data. Sediakan lisensi resmi disertai panduan penggunaan yang jelas.',
    impact: 3, effort: 1, horizon: '0_3M', owner_role: 'Head of IT', cost_band: '10_30jt',
    triggers: [{ question_code: 'PPL-05', max_score: 25 }],
  },
  {
    code: 'REC-TEC-001', dimension_code: 'TEC',
    title: 'Minta akses API ke vendor sistem inti atau bangun lapisan integrasi',
    body: 'Tanpa API, setiap integrasi AI akan bergantung pada ekspor manual yang rapuh. Masukkan klausul akses API pada perpanjangan kontrak vendor berikutnya.',
    impact: 4, effort: 3, horizon: '3_6M', owner_role: 'Head of IT', cost_band: '30_100jt',
    triggers: [{ question_code: 'TEC-02', max_score: 25 }],
  },
  {
    code: 'REC-TEC-002', dimension_code: 'TEC',
    title: 'Susun rencana modernisasi infrastruktur bertahap',
    body: 'Tidak perlu migrasi cloud total. Mulai dari beban kerja analitik yang paling membutuhkan elastisitas komputasi.',
    impact: 3, effort: 4, horizon: '6_12M', owner_role: 'Head of IT', cost_band: '100_500jt',
    triggers: [{ question_code: 'TEC-01', max_score: 25 }, { question_code: 'TEC-04', max_score: 0 }],
  },
  {
    code: 'REC-PRC-001', dimension_code: 'PRC',
    title: 'Dokumentasikan 3 proses inti yang paling mahal',
    body: 'AI mengotomasi proses, bukan kekacauan. Petakan langkah, pemilik, dan waktu tiap proses sebelum mencoba mengotomasinya.',
    impact: 3, effort: 2, horizon: '0_3M', owner_role: 'Manajer Operasional', cost_band: 'under_10jt',
    triggers: [{ question_code: 'PRC-01', max_score: 25 }],
  },
  {
    code: 'REC-PRC-002', dimension_code: 'PRC',
    title: 'Tetapkan KPI dengan pemilik untuk proses inti',
    body: 'Tanpa angka dasar, dampak AI tidak dapat dibuktikan dan anggaran lanjutan sulit dipertahankan.',
    impact: 4, effort: 2, horizon: '0_3M', owner_role: 'Manajer Operasional', cost_band: 'under_10jt',
    triggers: [{ question_code: 'PRC-05', max_score: 50 }],
  },
  {
    code: 'REC-FIN-001', dimension_code: 'FIN',
    title: 'Ukur biaya baseline proses target sebelum investasi',
    body: 'Hitung jam kerja, tingkat kesalahan, dan biaya rework proses yang ingin diperbaiki. Angka ini menjadi pembanding untuk membuktikan ROI.',
    impact: 5, effort: 1, horizon: '0_3M', owner_role: 'Finance', cost_band: 'under_10jt',
    triggers: [{ question_code: 'FIN-01', max_score: 50 }],
  },
  {
    code: 'REC-FIN-002', dimension_code: 'FIN',
    title: 'Sesuaikan ekspektasi waktu balik modal ke 6–18 bulan',
    body: 'Ekspektasi balik modal di bawah 3 bulan membuat proyek dihentikan sebelum sempat matang. Sepakati horizon yang realistis di awal bersama manajemen.',
    impact: 3, effort: 1, horizon: '0_3M', owner_role: 'C-Level', cost_band: 'under_10jt',
    triggers: [{ question_code: 'FIN-03', max_score: 50 }],
  },

  // ── Rekomendasi tingkat lanjut: tanpa pemicu, sehingga tidak pernah muncul
  // dari gap. Dipakai sebagai pengisi jaminan minimum (BA3) pada organisasi
  // yang sudah matang, agar mereka menerima langkah berikutnya alih-alih
  // disuruh mengerjakan hal yang sudah selesai.
  {
    code: 'REC-ADV-001', dimension_code: 'DAT',
    title: 'Bangun feature store dan pantau data drift',
    body: 'Fondasi data Anda sudah kuat. Langkah berikutnya adalah menyiapkan feature store agar fitur model dapat dipakai ulang lintas proyek, disertai pemantauan drift agar performa model tidak diam-diam menurun.',
    impact: 4, effort: 3, horizon: '3_6M', owner_role: 'Head of Data', cost_band: '30_100jt',
    triggers: [],
  },
  {
    code: 'REC-ADV-002', dimension_code: 'STR',
    title: 'Jalankan pilot AI berukuran kecil dengan kriteria keberhasilan tertulis',
    body: 'Kesiapan sudah memadai. Pilih satu use case bernilai tinggi, tetapkan metrik keberhasilan dan batas waktu evaluasi sebelum mulai, lalu jalankan sebagai pilot terbatas.',
    impact: 5, effort: 3, horizon: '3_6M', owner_role: 'Product & Head of Data', cost_band: '100_500jt',
    triggers: [],
  },
  {
    code: 'REC-ADV-003', dimension_code: 'GOV', 
    title: 'Siapkan proses evaluasi dan audit model berkala',
    body: 'Sebelum model masuk produksi, tetapkan siapa yang meninjau kualitas keluaran, seberapa sering, dan apa ambang untuk menarik model dari peredaran.',
    impact: 4, effort: 2, horizon: '3_6M', owner_role: 'Risk & Head of Data', cost_band: '10_30jt',
    triggers: [],
  },
  {
    code: 'REC-ADV-004', dimension_code: 'PPL',
    title: 'Bentuk komunitas praktik AI lintas divisi',
    body: 'Pertahankan momentum dengan forum rutin untuk berbagi eksperimen, kegagalan, dan pola yang berhasil, sehingga pengetahuan tidak terkunci di satu tim.',
    impact: 3, effort: 1, horizon: '3_6M', owner_role: 'HR & Head of Data', cost_band: 'under_10jt',
    triggers: [],
  },
  {
    code: 'REC-ADV-005', dimension_code: 'TEC',
    title: 'Siapkan jalur MLOps untuk penyajian dan pemantauan model',
    body: 'Tanpa jalur rilis model yang terkelola, pilot yang berhasil tetap sulit naik ke produksi. Siapkan pipeline pelatihan, penyajian, dan pemantauan sejak awal.',
    impact: 4, effort: 4, horizon: '6_12M', owner_role: 'Head of IT', cost_band: '100_500jt',
    triggers: [],
  },
  {
    code: 'REC-ADV-006', dimension_code: 'PRC',
    title: 'Rancang ulang proses agar manusia dan AI berbagi peran',
    body: 'Otomasi memberi hasil terbaik bila prosesnya dirancang ulang, bukan sekadar ditempeli alat. Tentukan langkah mana yang ditangani model dan di mana manusia melakukan verifikasi.',
    impact: 4, effort: 3, horizon: '6_12M', owner_role: 'Manajer Operasional', cost_band: '30_100jt',
    triggers: [],
  },
  {
    code: 'REC-ADV-007', dimension_code: 'FIN',
    title: 'Lacak nilai yang terealisasi dari setiap inisiatif AI',
    body: 'Bandingkan biaya baseline dengan hasil setelah implementasi setiap kuartal, sehingga keputusan melanjutkan atau menghentikan didasarkan pada angka.',
    impact: 4, effort: 2, horizon: '6_12M', owner_role: 'Finance', cost_band: 'under_10jt',
    triggers: [],
  },
]
